In [11]:
# numpy excerise
import numpy as np

In [12]:
# 1. Formthe 2-D array (without typing it in explicitly):
a = np.arange(1,16).reshape((3,-1)).T
a

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [13]:
#2. Divide each column of the array:
a = np.arange(25).reshape(5, 5)
b = np.array([1., 5, 10, 15, 20])
a/b

array([[  0.        ,   0.2       ,   0.2       ,   0.2       ,   0.2       ],
       [  5.        ,   1.2       ,   0.7       ,   0.53333333,   0.45      ],
       [ 10.        ,   2.2       ,   1.2       ,   0.86666667,   0.7       ],
       [ 15.        ,   3.2       ,   1.7       ,   1.2       ,   0.95      ],
       [ 20.        ,   4.2       ,   2.2       ,   1.53333333,   1.2       ]])

In [14]:
#3. Harder one: Generate a 10 x 3 array of random numbers (in range [0,1]). For each row, pick the number
#closest to 0.5.
#• Use abs and argsort to find the column j closest for each row.
#• Use fancy indexing to extract the numbers. (Hint: a[i,j] – the array i must contain the row numbers
#corresponding to stuff in j.)
x = np.random.uniform(low=0, high=1, size=(10,3))
x

array([[ 0.12462623,  0.99551081,  0.64143702],
       [ 0.84068088,  0.20757905,  0.7116011 ],
       [ 0.88942802,  0.97966667,  0.70435898],
       [ 0.00820113,  0.51995048,  0.29595437],
       [ 0.46915861,  0.97527749,  0.81087241],
       [ 0.63039804,  0.93457028,  0.51702183],
       [ 0.54151333,  0.73366045,  0.11428047],
       [ 0.57926693,  0.53070964,  0.00119101],
       [ 0.44898408,  0.51047831,  0.51546549],
       [ 0.15882887,  0.54695435,  0.57601252]])

In [23]:
y = [np.argmin(abs(x-0.5),axis=1)]
x[np.arange(x.shape[0]),y]

array([[ 0.64143702,  0.7116011 ,  0.70435898,  0.51995048,  0.46915861,
         0.51702183,  0.54151333,  0.53070964,  0.51047831,  0.54695435]])