In [76]:
import numpy as np
from scipy.spatial import distance
np.random.seed(73)

In [91]:
def meanCentroids(data,clusters):
    """
        input : data and where data belongs(clusters)
        output : mean centroid of data clusters 
    """
    k = np.max(clusters) + 1
    results = np.zeros(shape=(k,data.shape[1]),dtype=np.float64)
    for i in range(k):
        results[i] = np.mean(data[clusters==i],axis=0)
    return results
# test case
data = np.array([[12, 10, 87],
                 [ 2, 12, 33],
                 [68, 31, 32],
                 [88, 13, 66],
                 [79, 40, 89],
                 [ 1, 77, 12]])
meanCentroids(data,np.array([1, 1, 2, 2, 0, 1]))

array([[ 79.,  40.,  89.],
       [  5.,  33.,  44.],
       [ 78.,  22.,  49.]])

In [165]:
np.random.seed(199)
def kmeans(data, k, steps=20):
    centroids = data[np.random.choice(np.arange(len(data)), k, False)]
    # two different way init array
#     centroids =  data[np.random.randint(len(data),size=k)]
    print(centroids)
    for i in range(steps):
        distances  = distance.cdist(centroids,data,'sqeuclidean')
        clusters = np.argmin(distances,axis=0)
#        print(distances.shape,i,clusters.shape)
#         print(clusters,i)
        new_centroids = meanCentroids(data,clusters)
        centroids = new_centroids
    return clusters,centroids
data = np.array([[12, 10, 87],
                 [ 2, 12, 33],
                 [68, 31, 32],
                 [88, 13, 66],
                 [79, 40, 89],
                 [ 1, 77, 12]])
kmeans(data,k=3)

[[ 1 77 12]
 [ 2 12 33]
 [68 31 32]]


(array([1, 1, 2, 2, 2, 0]), array([[  1.        ,  77.        ,  12.        ],
        [  7.        ,  11.        ,  60.        ],
        [ 78.33333333,  28.        ,  62.33333333]]))